### ISSUE TITLE
Game stops on player error but should it?

### ISSUE THREAD

**Issue by raaperrotta** [raaperrotta/nothanks#3]
We should catch exceptions raised in player modules within nothanks.Game. What should the default behavior be?

I suggest:
Pass is the player has any coins, take only when needed (just like the nothanks.Player base class).

**Comment by ginop** [comment]
Agreed. That seems simple enough for now.

**Comment by raaperrotta** [comment]
If I was better at using git I would switch to a new branch, implement this, then merge the changes I have been working on since the last commit. But I don't trust myself to do that correctly so I will implement this right after I commit my current work.

**Comment by raaperrotta** [comment]
We discussed handling an error when the player takes a turn. Handling an error in the update function is easy enough (just ignore it). But what about setting up for new game? I guess also ignore it. If the player fails to reset between games only that player is affected.

**Comment by raaperrotta** [comment]
Added these in commit c660566123e7450f78470173ce3d7e3f5a0c0ec9
