### ISSUE TITLE
Need better nothanks Game testing

### ISSUE THREAD

**Issue by raaperrotta** [raaperrotta/nothanks#4]
I botched my git control apparently and have been working with an outdated version of nothanks.Game that played the game incorrectly! (It never dealt the last card and rotated players even after taking a card.)

This should have been obvious based on our unit testing. We should add tests to make sure the game rules are implemented correctly.

**Comment by ginop** [comment]
I don't have a lot of experience with unit testing. What will be
implemented to check that (just a simple game with known outcome?), and how
often will units be tested?

**Comment by raaperrotta** [comment]
I took a crack at this. The way I implemented the gameplay wasn't very testable. I broke it into three pieces so that each of those can be tested and I added tests for `nothanks.Game.player_action` and `nothanks.Game.update_game` in `test_nothanks.py`.

**Comment by raaperrotta** [comment]
I am implementing unit tests following a pretty vanilla approach. I am using [pytest](https://docs.pytest.org/en/latest/), which finds python files that start or end with `test` and runs the functions inside it that also start or end with `test`. Inside those functions, I use `assert` statements to check that the expected condition is true, and do some checking to see that things do or don't raise exceptions as expected.

Then pytest can be run at the command line simply by executing `pytest`. There are options for executing a specific file or test but we have so few at this point and they run so fast that I always just run them all.

In addition to that, whenever a commit is made to GitHub, the continuous integration service Travis-CI runs all our tests automatically.
